### ISSUE TITLE
Nefunguje prehravani The Voice Zone ani The Voice Cesko Slovensko

### ISSUE THREAD

**Issue by starkskalle** [kodi-czsk/plugin.video.dmd-czech.novaplus#27]
Dnes jsem cerstve nainstaloval tento plugin a nefunguje mi. Delam neco spatne? Pri kliknuti na  polozku The Voice Zone nebo The Voice Cesko Slovensko to hodi error "Vice informaci najdete v protokolu". 

V logu jsem nasel neco nasledujiciho:
`2019-05-19 11:55:12.746 T:1937295760   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-05-19 11:55:22.519 T:1673028464   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'getText'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.dmd-czech.novaplus/default.py", line 249, in <module>
                                                VIDEOLINK(url,page)
                                              File "/storage/.kodi/addons/plugin.video.dmd-czech.novaplus/default.py", line 112, in VIDEOLINK
                                                desc = article.find('div', 'e-description').getText(" ").encode('utf-8')
                                            AttributeError: 'NoneType' object has no attribute 'getText'
                                            -->End of Python script error report<--
2019-05-19 11:55:22.632 T:1480143728   ERROR: GetDirectory - Error getting plugin://plugin.video.dmd-czech.novaplus/?mode=2&name=The%20Voice%20Zone&page=1&url=https%3a%2f%2fnovaplus.nova.cz%2fporad%2fthe-voice-zone
2019-05-19 11:55:22.634 T:1937295760   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dmd-czech.novaplus/?mode=2&name=The%20Voice%20Zone&page=1&url=https%3a%2f%2fnovaplus.nova.cz%2fporad%2fthe-voice-zone) failed
2019-05-19 11:56:43.889 T:1501385584   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'getText'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.dmd-czech.novaplus/default.py", line 249, in <module>
                                                VIDEOLINK(url,page)
                                              File "/storage/.kodi/addons/plugin.video.dmd-czech.novaplus/default.py", line 112, in VIDEOLINK
                                                desc = article.find('div', 'e-description').getText(" ").encode('utf-8')
                                            AttributeError: 'NoneType' object has no attribute 'getText'
                                            -->End of Python script error report<--
2019-05-19 11:56:44.021 T:1454326640   ERROR: GetDirectory - Error getting plugin://plugin.video.dmd-czech.novaplus/?mode=2&name=The%20Voice%20%c4%8cesko%20Slovensko&page=1&url=https%3a%2f%2fnovaplus.nova.cz%2fporad%2fthe-voice
2019-05-19 11:56:44.022 T:1937295760   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.dmd-czech.novaplus/?mode=2&name=The%20Voice%20%c4%8cesko%20Slovensko&page=1&url=https%3a%2f%2fnovaplus.nova.cz%2fporad%2fthe-voice) failed
2019-05-19 11:56:49.026 T:1520706416   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/221ffcb7-947d-43f7-b51f-2fadf01c464e.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.037 T:1474286448   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/f92825db-3523-4181-86f9-1c73ed4faeba.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.040 T:1482679152   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/84a66ed4-81c7-48f3-bcb8-619521479995.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.045 T:1529099120   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/rx/6854f646-51b8-47e9-8ec7-d0a454174ee8.jpg m_image_size zero
2019-05-19 11:56:49.050 T:1482679152  NOTICE: LoadJpeg: unable to load https://cloudia.cms.nova.cz/r620x350n/84a66ed4-81c7-48f3-bcb8-619521479995.jpg?default=episode
2019-05-19 11:56:49.059 T:1529099120  NOTICE: LoadJpeg: unable to load https://cloudia.cms.nova.cz/rx/6854f646-51b8-47e9-8ec7-d0a454174ee8.jpg
2019-05-19 11:56:49.145 T:1520706416   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/221ffcb7-947d-43f7-b51f-2fadf01c464e.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.169 T:1520706416  NOTICE: LoadJpeg: unable to load https://cloudia.cms.nova.cz/r620x350n/221ffcb7-947d-43f7-b51f-2fadf01c464e.jpg?default=episode
2019-05-19 11:56:49.202 T:1474286448   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/f92825db-3523-4181-86f9-1c73ed4faeba.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.224 T:1474286448  NOTICE: LoadJpeg: unable to load https://cloudia.cms.nova.cz/r620x350n/f92825db-3523-4181-86f9-1c73ed4faeba.jpg?default=episode
2019-05-19 11:56:49.320 T:1482679152   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/0e709dcc-c633-4e92-8537-fbe7ea3cf3cd.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.368 T:1482679152   ERROR: Previous line repeats 1 times.
2019-05-19 11:56:49.368 T:1482679152  NOTICE: LoadJpeg: unable to load https://cloudia.cms.nova.cz/r620x350n/0e709dcc-c633-4e92-8537-fbe7ea3cf3cd.jpg?default=episode
2019-05-19 11:56:49.389 T:1474286448   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/b67fcd53-67ff-4470-9dcd-8c1fc306cfb6.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.521 T:1474286448   ERROR: Previous line repeats 1 times.
2019-05-19 11:56:49.521 T:1474286448  NOTICE: LoadJpeg: unable to load https://cloudia.cms.nova.cz/r620x350n/b67fcd53-67ff-4470-9dcd-8c1fc306cfb6.jpg?default=episode
2019-05-19 11:56:49.567 T:1520706416   ERROR: COMXImageFile::ReadFile https://cloudia.cms.nova.cz/r620x350n/8055f3cd-c17d-4c6c-81c8-99dbf2e1ff68.jpg?default=episode m_image_size zero
2019-05-19 11:56:49.625 T:1520706416   ERROR: Previous line repeats 1 times.
2019-05-19 11:56:49.630 T:1520706416  NOTICE: LoadJpeg: unable to load https://cloudia.cms.nova.cz/r620x350n/8055f3cd-c17d-4c6c-81c8-99dbf2e1ff68.jpg?default=episode
2019-05-19 11:56:53.399 T:1937295760  NOTICE: VideoPlayer::OpenFile: https://nova-cms-avod.ssl.cdn.cra.cz/ggKt6N7TGXR9ykL7kxr_Uw==,1558268464/media/vod/2019/04/30/e7e377db-d15a-42a5-8867-d633974c5eb8-mp4-lq.mp4
2019-05-19 11:56:53.415 T:1501385584  NOTICE: Creating InputStream
2019-05-19 11:56:53.691 T:1501385584  NOTICE: Creating Demuxer
2019-05-19 11:56:54.487 T:1501385584  NOTICE: Opening stream: 0 source: 256
2019-05-19 11:56:54.487 T:1501385584  NOTICE: Creating video codec with codec id: 27
2019-05-19 11:56:54.504 T:1501385584  NOTICE: Creating video thread
2019-05-19 11:56:54.504 T:1491071856  NOTICE: running thread: video_thread
2019-05-19 11:56:54.583 T:1501385584  NOTICE: Opening stream: 1 source: 256
2019-05-19 11:56:54.583 T:1501385584  NOTICE: Finding audio codec for: 86018
2019-05-19 11:56:54.585 T:1501385584  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2019-05-19 11:56:54.585 T:1501385584  NOTICE: Creating audio thread
2019-05-19 11:56:54.585 T:1418658672  NOTICE: running thread: CVideoPlayerAudio::Process()
2019-05-19 11:56:54.597 T:1418658672  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
2019-05-19 11:56:58.299 T:1937295760  NOTICE: CVideoPlayer::CloseFile()
2019-05-19 11:56:58.302 T:1501385584  NOTICE: CVideoPlayer::OnExit()
2019-05-19 11:56:58.302 T:1501385584  NOTICE: Closing stream player 1
2019-05-19 11:56:58.302 T:1501385584  NOTICE: Waiting for audio thread to exit
2019-05-19 11:56:58.340 T:1418658672  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2019-05-19 11:56:58.341 T:1501385584  NOTICE: Closing audio device
2019-05-19 11:56:58.351 T:1937295760  NOTICE: VideoPlayer: waiting for threads to exit
2019-05-19 11:56:58.392 T:1501385584  NOTICE: Deleting audio codec
2019-05-19 11:56:58.392 T:1501385584  NOTICE: Closing stream player 2
2019-05-19 11:56:58.393 T:1501385584  NOTICE: waiting for video thread to exit
2019-05-19 11:56:58.394 T:1491071856  NOTICE: thread end: video_thread
2019-05-19 11:56:58.396 T:1501385584  NOTICE: deleting video codec
2019-05-19 11:56:58.426 T:1937295760  NOTICE: VideoPlayer: finished waiting
2019-05-19 11:56:58.426 T:1937295760  NOTICE: CVideoPlayer::CloseFile()
2019-05-19 11:56:58.426 T:1937295760  NOTICE: VideoPlayer: waiting for threads to exit
2019-05-19 11:56:58.426 T:1937295760  NOTICE: VideoPlayer: finished waiting
2019-05-19 11:56:58.939 T:1937295760   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
`

Diky za jakoukoliv radu :)

**Comment by elring** [comment]
Je to chyba doplňku (nebo stránek NovaPlus, jak se to vezme :-)) 
Každopádně pořady Voice nemají na stránkách vyplněn popis pořadu/dílu, s čímž doplněk nepočítá. Opravil jsem doplněk, můžete ho zatím zkusit stáhnout a aktualizovat ručně z https://github.com/elring/plugin.video.dmd-czech.novaplus/archive/master.zip
Po potvrzení ho pošlu dál k začlenění do oficiální distribuce.

**Comment by starkskalle** [comment]
Dik, za super rychly fix. Potvrzuji, ze ted uz to nacte jednotlive dostupne dily a je mozne je i spoustet. Diky moc!
